import { GENERATION, RESOURCES } from "../data/constants.js";
import { RiftsData } from "../data/rifts_data.js";
import { Rift } from "../entities/rift.js";

export class RiftsManager {
    rifts = [];
    riftsData;

    constructor() {
        // Generate the generic Rift Data (such as Rift Level Up requirements)
        this.riftsData = new RiftsData();

        // Loop through all Resources
        Array.from(Object.values(RESOURCES)).forEach(resource => {
            // If this is a Tier 1 Resource
            if (resource.TIER === 1) {
                // We create a new Rift for it
                this.rifts[resource.ID] = new Rift(resource.ID, 1);
            }
        });
    }

    /**********************************************
     * GETTERS
     *********************************************/
    /**
     * Get the current level of the Rift for the specified Resource
     * @param {string} _resourceId ID of the Rift's Resource
     * @returns The current level of the Rift, or 1 if no Rift found for this element
     */
    getRiftLevel = _resourceId => {
        if (undefined === this.rifts[_resourceId]) {
            return 1;
        }
        return this.rifts[_resourceId].getLevel();
    }

    /**
     * Get how much of its Resource the Rift currently generates
     * @param {string} _resourceId ID of the Rift's Resource
     * @returns The amount of the Resource generated by the Rift, or 1 if no Rift found for this element
     */
    getRiftAmountGenerated = _resourceId => {
        return (this.rifts[_resourceId] === undefined ? 1 : this.rifts[_resourceId].getAmountGenerated());
    }

    /**
     * Get the image name corresponding to the specified Resources's Rift
     * @param {string} _resourceId ID of the Rift's Resource
     * @returns The name of the image, or "UnknownRift" if no Rift for that Resource was found
     */
    getImageName = _resourceId => {
        if (undefined === this.rifts[_resourceId]) {
            return "UnknownRift";
        }

        return this.rifts[_resourceId].getImageName();
    }

    /**
     * Get the alternative text for the image corresponding to the specified Resource's Rift
     * @param {string} _resourceId ID of the Rift's Resource
     * @returns The alternative text of the image, or "Unknown Rift" if no Rift for that Resource was found
     */
    getImageAlt = _resourceId => {
        if (undefined === this.rifts[_resourceId]) {
            return "Unknown Rift";
        }

        return this.rifts[_resourceId].getImageAlt();
    }

    /**
     * Levels up the Rift of the specified Resource, if it exists
     * @param {string} _resourceId ID of the Rift's Resource
     */
    levelUpRift = (_resourceId) => {
        if (undefined === this.rifts[_resourceId]) {
            return;
        }

        this.updateRiftLevel(_resourceId, this.rifts[_resourceId].getLevel() + 1);
    }

    /**
     * Sets the Rift from the specified Resource to the level passed in
     * @param {string} _resourceId ID of the Rift's Resource
     * @param {Number} newLevel The new level of the Rift
     */
    updateRiftLevel = (_resourceId, newLevel) => {
        if (undefined === this.rifts[_resourceId] || newLevel < 1 || newLevel > GENERATION[_resourceId].length) {
            return;
        }

        this.rifts[_resourceId].setLevel(newLevel);
    }

    /**
     * Get the requirements to level up the Rift of the desired Resource
     * @param {string} _resourceId ID of the Rift's Resource
     * @returns a the Resource(s) and amount(s) required to level up the Rift of the specified element, with format [[{RESOURCE: resourceID, AMOUNT: number}]]
     */
    getNextLevelRequirement = _resourceId => {
        if (this.rifts[_resourceId] === undefined) {
            return null;
        }
        
        // We return the object with a list of all the requirements to level up the Rift of the specified Resource
        return this.riftsData.getLevelUpRequirements(this.rifts[_resourceId].getLevel(), _resourceId);
    }
}