import { GENERATION, RESOURCES } from "../data/constants.js";
import { RiftsData } from "../data/rifts_data.js";
import { Rift } from "../entities/rift.js";

export class RiftsManager {
    rifts = [];
    riftsData;

    constructor() {
        // Generate the generic Rift Data (such as Rift Level Up requirements)
        this.riftsData = new RiftsData();

        // Loop through all Resources
        Array.from(Object.values(RESOURCES)).forEach(resource => {
            // If this is a Tier 1 Resource
            if (resource.TIER === 1) {
                // We create a new Rift for it
                this.rifts[resource.ELEMENT] = new Rift(resource.ELEMENT, 1);
            }
        });
    }

    /**********************************************
     * GETTERS
     *********************************************/
    /**
     * Get the current level of the Rift for the specified Element
     * @param {string} elementId ID of the Rift's Element
     * @returns The current level of the Rift, or 1 if no Rift found for this element
     */
    getRiftLevel = elementId => {
        if (undefined === this.rifts[elementId]) {
            return 1;
        }
        return this.rifts[elementId].getLevel();
    }

    /**
     * Get how much of the Resource the Rift of the specified Element currently generates
     * @param {string} elementId ID of the Rift's Element
     * @returns The amount of the Resource generated by the Rift, or 1 if no Rift found for this element
     */
    getRiftAmountGenerated = elementId => {
        return (this.rifts[elementId] === undefined ? 1 : this.rifts[elementId].getAmountGenerated());
    }

    /**
     * Get specified Element's Rift's image name
     * @param {string} elementId ID of the Rift's Element
     * @returns The name of the image, or "UnknownRift" if no Rift of that Element was found
     */
    getImageName = elementId => {
        if (undefined === this.rifts[elementId]) {
            return "UnknownRift";
        }

        return this.rifts[elementId].getImageName();
    }

    /**
     * Get specified Element's Rift's alternative text for the image
     * @param {string} elementId ID of the Rift's Element
     * @returns The alternative text of the image, or "Unknown Rift" if no Rift of that Element was found
     */
    getImageAlt = elementId => {
        if (undefined === this.rifts[elementId]) {
            return "Unknown Rift";
        }

        return this.rifts[elementId].getImageAlt();
    }

    /**
     * Levels up the Rift of the specified Element, if it exists
     * @param {string} elementId ID of the Rift's Element
     */
    levelUpRift = (elementId) => {
        if (undefined === this.rifts[elementId]) {
            return;
        }

        this.updateRiftLevel(elementId, this.rifts[elementId].getLevel() + 1);
    }

    /**
     * Sets the Rift from the specified Element to the level passed in
     * @param {string} elementId ID of the Rift's Element
     * @param {Number} newLevel The new level of the Rift
     */
    updateRiftLevel = (elementId, newLevel) => {
        if (undefined === this.rifts[elementId] || newLevel < 1 || newLevel > GENERATION[elementId].length) {
            return;
        }

        this.rifts[elementId].setLevel(newLevel);
    }

    /**
     * Get the requirements to level up the Rift of the desired Element
     * @param {string} elementId ID of the Rift's Element
     * @returns a the Resource(s) and amount(s) required to level up the Rift of the specified element, with format [[{RESOURCE: resourceID, AMOUNT: number}]]
     */
    getNextLevelRequirement = elementId => {
        if (this.rifts[elementId] === undefined) {
            return null;
        }
        
        // We return the object with a list of all the requirements to level up the Rift of the specified Element
        return this.riftsData.getLevelUpRequirements(this.rifts[elementId].getLevel(), elementId);
    }
}